echo "; variables.asm - header file of data segment addresses"
echo ";                 to make up for the lack of linking"
echo ";"
echo "; Generated by genvars.sh"
echo
awk <data.map -e 'BEGIN{a=0} /Section DATA/{a=1;next} /^Real/{next} a && $1 != "" { printf "%-35s equ 0x%s\n", $3, $1; }'
echo
echo "; vi""m: syntax=nasm"
