echo "; variables.asm - header file of data segment addresses"
echo ";                 to make up for the lack of linking"
echo ";"
echo "; Generated by genvars.sh"
echo
<data.map sed -e '0,/^---- Section DATA/d' -e '/^Real/d' | awk '$1 != "" { printf "%-35s equ 0x%s\n", $3, $1;}'
echo
echo "; vi""m: syntax=nasm"
