#!/usr/bin/env python3
import sys

print("digraph {")
currentfunc = "top"
currentlabel = "top"
lastjump = ""
for line in sys.stdin:
    words = line.strip().split()
    if not words:
        continue
    if words[0].endswith(":"):
        label = words[0].strip(":")
        if label.startswith('.'):
            if lastjump != "jmp":
                print("  \"{}\" -> \"{}\" [color=blue];".format(currentlabel, currentfunc+label))
            currentlabel = currentfunc+label
        else:
            currentfunc = label
            currentlabel = label
        lastjump = ""
        print("  \"{}\" [label=\"{}\"]".format(currentlabel, label))
    if words[0].startswith("j"):
        lastjump = words[0]
        for word in words:
            if word.startswith("."):
                target = currentfunc+word
                if words[0] == "jmp":
                    print("  \"{}\" -> \"{}\" [color=purple];".format(currentlabel, target))
                else:
                    print("  \"{}\" -> \"{}\";".format(currentlabel, target))
print("}")
