#!/usr/bin/env python3
import sys

print("digraph code {")
currentfunc = "top"
currentlabel = "top"
lastjump = ""
for line in sys.stdin:
    words = line.strip().split()
    if not words:
        continue
    if words[0] == "func" or words[0].endswith(":") and "%" not in words[0]:
        if words[0] == "func":
            label = words[1]
        else:
            label = words[0].strip(":")
        if label.startswith('.'):
            if lastjump != "jmp":
                print("  \"{}\" -> \"{}\" [color=blue];".format(currentlabel, currentfunc+label))
            currentlabel = currentfunc+label
        else:
            currentfunc = label
            currentlabel = label
        lastjump = ""
        shape = "ellipse" if "." in label else "box"
        print("  \"{}\" [label=\"{}\", shape={}]".format(currentlabel, label, shape))
    if words[0].startswith("j") or words[0] == "dw":
        for word in words:
            if word.startswith("."):
                lastjump = words[0]
                target = currentfunc+word
                if words[0] == "jmp" or words[0] == "dw":
                    print("  \"{}\" -> \"{}\" [color=purple];".format(currentlabel, target))
                else:
                    print("  \"{}\" -> \"{}\";".format(currentlabel, target))
print("}")
