name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3

    # Ubuntu has an outdated version of nasm (2.13)
    # so we need this special action to grab a newer version.
    # Could replace with apt-get when Github moves to a newer ubuntu release.
    - name: Set up NASM
      uses: ilammy/setup-nasm@v1.2.0
      with:
        version: 2.14.02

    - name: make
      run: make

    - name: make checksum
      run: make checksum
